version: build-{build}-{branch}

# all the Python versions, both 32-bit and 64-bit, listed at:
# https://www.appveyor.com/docs/windows-images-software/#python
image: Visual Studio 2022

environment:
  matrix:
    - PYTHON: "C:\\Python313"
    - PYTHON: "C:\\Python312"
    - PYTHON: "C:\\Python311"
    - PYTHON: "C:\\Python310"
    - PYTHON: "C:\\Python39"
    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python37"

init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"

install:
#  - ps: |
#      if (-not (Test-Path $env:PYTHON)) {
#        curl -o install_python.ps1 https://raw.githubusercontent.com/matthew-brett/multibuild/11a389d78892cf90addac8f69433d5e22bfa422a/install_python.ps1
#        .\install_python.ps1
#      }
  - ps: if (-not (Test-Path $env:PYTHON)) { throw "No $env:PYTHON" }
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python --version
  - pip install -U virtualenv  # upgrade pip in tox's virtualenvs
  - pip install tox
  - pip install tqdm

build: off

test_script:
  - python test.py
